steps:
- id: build-builder
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--rm=false', '-t', 'gcr.io/$PROJECT_ID/tape4nmt-builder', '-f', 'Dockerfile', '.']

- id: test
  name: 'gcr.io/$PROJECT_ID/tape4nmt-builder'
  args: [ 'ducttape', 'test.tape', '-y' ]
