steps:
- name: 'ubuntu'
  args: ['bash', 'echo', 'hello']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/Dockerfile', '.']
images: ['gcr.io/$PROJECT_ID/Dockerfile']
